[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  publish = "dist"
  functions = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  timeout = 30 # Zwiększ limit czasu do 30 sekund
